### ISSUE TITLE
stellopt_reinit_vmec allocation issue

### ISSUE THREAD

**Issue by landreman** [PrincetonUniversity/STELLOPT#101]
https://github.com/PrincetonUniversity/STELLOPT/blob/47dad57a9688e47670cb925adf9b46f725d3c71c/STELLOPTV2/Sources/General/stellopt_reinit_vmec.f90#L187

I think this line should have `rbcc` instead of `rbss`, as in the corresponding line of VMEC's `readin.f`:

https://github.com/PrincetonUniversity/STELLOPT/blob/47dad57a9688e47670cb925adf9b46f725d3c71c/VMEC2000/Sources/Input_Output/readin.f#L670

At least in tests of our python VMEC interface https://github.com/hiddenSymmetries/VMEC2000 , in some circumstances `SIZE(rbss,1)` returns a garbage value, so that line of reinit can cause huge amounts of memory to be allocated unnecessarily. I'm not sure if this is also a problem in stellopt in practice. @lazersos Do you recall if there is a reason for this line of `stellopt_reinit_vmec.f90` to differ from `readin.f`?

**Comment by lazersos** [comment]
Let's fix that!

**Comment by lazersos** [comment]
@landreman So I think the reason I used `rbss` instead of `rbcc` is because of how the variable is used:
```fortran

      IF (lconm1 .and. (lthreed .or. lasym)) THEN
         ALLOCATE (temp(SIZE(rbss,1)))
         IF (lthreed) THEN
            mj = 1+joff
            temp = rbss(:,mj)
            rbss(:,mj) = p5*(temp(:) + zbcs(:,mj))
            zbcs(:,mj) = p5*(temp(:) - zbcs(:,mj))
         END IF
         IF (lasym) THEN
            mj = 1+joff
            temp = rbsc(:,mj)
            rbsc(:,mj) = p5*(temp(:) + zbcc(:,mj))
            zbcc(:,mj) = p5*(temp(:) - zbcc(:,mj))
         END IF
         IF (ALLOCATED(temp)) DEALLOCATE (temp)
      END IF
```
So it makes sense for temp to be the size of `rbss` since `temp=rbss(:,mj)` is used.  Although I can confirm that in the ORNL branch the line reads `ALLOCATE (temp(SIZE(rbcc,1)))`.  

It shouldn't matter as both `rbss` and `rbcc` should be `ntor+1` sized.  Although there may be an issue if `ntmax` isn't being set correctly.  `rbcc` is a pointer `rbss => rmn_bdy(:,:,rss)` where `rss=2` if `lthreed=.true.` or `lasym=.true.`.  This is handled in `read_indata.f` so it could be that `read_indata` hasn't been called on the thread executing VMEC causing your python issue.  I'm going to stick with `ALLOCATE(temp(SIZE(rbss,1)))` being the correct statement.
