### ISSUE TITLE
BEAMS3D: Handling of the poloidal field sign from EQDSK files

### ISSUE THREAD

**Issue by kudav** [PrincetonUniversity/STELLOPT#153]
When running BEAMS3D with an EQDSK file, there seems to be an inconsistency in the handling of the poloidal field sign. When converting the equilibrium to VMEC, the sign is handled correctly, seen below on the left plot as negative B_Z on the outboard midplane (I_tor is in positive Phi direction). However, B_Z in BEAMS3D has reversed sign, as seen on the right plot.
![grafik](https://user-images.githubusercontent.com/72251199/164469008-e96e7486-3875-45d4-89f5-1486fae0b2c7.png)

**Comment by lazersos** [comment]
@kudav Just to be clear this is `g30841.03901` and the toroidal magnetic field is in the negative phi direction when viewed top down and the toroidal current is in the positive phi direction when viewed from the top down?

**Comment by lazersos** [comment]
The issue boils down to [COCOS Conventions](https://www.sciencedirect.com/science/article/pii/S0010465512002962) and the gfiles themselves.  Now for BEAMS3D we want physical quantities in MKS units with phi counter-clockwise as viewed from above (COCOS=11).  However the G-files can be various COCOS conventions, although it's safe to assume they assume the same toroidal angle convention so COCOS=1,3,5,7 are possible.

A fixed has been pushed to the `Lazerson` branch.

**Comment by lazersos** [comment]
Just to follow up on this issue.  This is far more complicated that I'd like.  However, BEAMS3D is COCOS 11 as far as I can tell.  The problem is that EQDSK files (gfiles) can be any one of number of COCOS formats, and it's hard to tell from just looking at the data, what format the file is in.  What I can say is that for COCOS=1,11 (and possibly 3) formatted files BEAMS3D reads them and generates the magnetic field correctly.
